version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - "9002:9000"
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
